pipeline:
  hugo-check:
    image: nossas/bonde-docs
    commands:
      - hugo check
    when:
      event: [push, tag]

pipeline:
  publish-docker:
    image: plugins/docker
    repo: nossas/bonde-docs
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  publish:
    image: plugins/docker
    repo: nossas/bonde-docs
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  deploy-rancher-bonde-docs:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: partners/bonde-docs
    docker_image: nossas/bonde-docs:${DRONE_BRANCH}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix-*, release-*, feature-*, develop]

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: bonde_bots
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
