site_name: BONDE Docs
nav:
  - Home: index.md
  - Checkout Hotmart - Estrutura de Assinatura: hotmart-checkout.md
  - Funil de vendas:
    - Etapa 1 – Aquisição e Qualificação Inicial (ActiveCampaign Native): funil-de-vendas/Etapa 1 – Aquisição e Qualificação Inicial (ActiveCampaign Native).md
    - Etapa 4 - Venda (Pós-Live).md: funil-de-vendas/Etapa 4 - Venda (Pós-Live).md
  - Roteiro de testes:
    - Perfil Contato (Aluno em potencial): roteiro-de-testes/Perfil Contato (Aluno em potencial).md
  - Fluxogramas: fluxogramas.md
  - Fluxos de automação:
    - Visão Geral: fluxos-integracoes/Visão Geral.md
    - Dependências e Impactos: fluxos-integracoes/Dependências e Impactos.md
    - Fluxo 1 - Enriquecimento de Base AC: fluxos-integracoes/Fluxo 1 - Enriquecimento de Base AC.md
    - Fluxo 2 - Gerenciamento de Acesso: fluxos-integracoes/Fluxo 2 - Gerenciamento de Acesso.md
    - Fluxo 3 - Ativação de Conta: fluxos-integracoes/Fluxo 3 - Ativação de Conta.md
    - Fluxo 4 - Desativação de Conta: fluxos-integracoes/Fluxo 4 - Desativação de Conta.md
    - Fluxo 5 - Sincronização de Perfil: fluxos-integracoes/Fluxo 5 - Sincronização de Perfil.md

theme: material

# Extensões necessárias para o Mermaid
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format